apiVersion: batch/v1
kind: CronJob
metadata:
  name: asyncstatus-executor
  namespace: delete-asyncstatus-project-in-case-inactivity
spec:
  schedule: "59 23 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: delete-asyncstatus-project-in-case-inactivity-executor
        spec:
          imagePullSecrets:
          - name: harbor-registry
          containers:
          - name: executor
            image: harbor.rent2door.pl/delete-asyncstatus-project-in-case-inactivity/executor:20250421120710 # {"$imagepolicy": "delete-asyncstatus-project-in-case-inactivity:delete-asyncstatus-project-in-case-inactivity-executor"}
            imagePullPolicy: Always
            command: ["/bin/sh", "-c"]
            args: ["python3 cli.py"]
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-settings
                  key: github_token
                  required: true
          restartPolicy: OnFailure
