on:
  push:
    branches:
      - main
    paths-ignore:
      - kubernetes/**

jobs:
  create-project-in-registry:
    runs-on: ubuntu-latest
    steps:

      - name: Create Project in Docker Registry
        run: |
          AUTH_TOKEN=$(echo -n "${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_SECRET }}" | base64)
          curl -X 'POST' \
          'https://${{ vars.DOCKER_URL }}/api/v2.0/projects' \
          -H 'accept: application/json' \
          -H 'X-Resource-Name-In-Location: false' \
          -H "authorization: Basic $AUTH_TOKEN" \
          -H 'Content-Type: application/json' \
          -d '{                                                                                                                     
          "project_name": "delete-asyncstatus-project-in-case-inactivity",
            "public": false,
              "metadata": {
                "public": "false",
                "auto_scan": "true",
                "auto_sbom_generation": "true"
              }
          }'

  build-app:
    runs-on: ubuntu-latest
    needs: create-project-in-registry
    strategy:
      matrix:
        service: [executor]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_URL }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          platforms: linux/amd64
          tags: ${{ vars.DOCKER_URL }}/delete-asyncstatus-project-in-case-inactivity/${{ matrix.service }}:000,${{ vars.DOCKER_URL }}/delete-asyncstatus-project-in-case-inactivity/${{ matrix.service }}:${{ env.TIMESTAMP }}
          cache-from: type=registry,ref=${{ vars.DOCKER_URL }}/delete-asyncstatus-project-in-case-inactivity/${{ matrix.service }}:000
